# Generated by Django 5.0.1 on 2024-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.IntegerField(max_length=8)),
                ('userConfirmpassword', models.IntegerField(max_length=8)),
            ],
        ),
    ]
